/**
 * Wire protocol shared by the browser and the Worker.
 *
 * Kept free of imports from either side so both can depend on it without
 * dragging in React or Workers types.
 */

/** What a session is allowed to do. */
export type Role = 'owner' | 'editor' | 'viewer'

export function canEdit(role: Role): boolean {
  return role === 'owner' || role === 'editor'
}

/**
 * A plan edit, as sent over the wire.
 *
 * These mirror the store's actions but carry only what the server needs to
 * re-apply them. Ids are generated by the client so an operation is
 * idempotent: replaying it produces the same result rather than a duplicate.
 */
export type Op =
  | { type: 'moveTracks'; trackIds: string[]; beforeId: string | null; sectionId?: string }
  | { type: 'setTrackSection'; trackIds: string[]; sectionId: string }
  | { type: 'addSection'; id: string; name: string; color: string }
  | { type: 'updateSection'; id: string; patch: { name?: string; color?: string } }
  | { type: 'deleteSection'; id: string }
  | { type: 'moveSection'; id: string; delta: number }
  | { type: 'addTracks'; tracks: unknown[] }
  /**
   * Reconcile the library against a fresh read of the Spotify playlist:
   * add what is new, update what changed, and drop what is no longer
   * there. Unlike `addTracks` this can remove, which is what makes a
   * re-import reflect a song deleted in Spotify.
   */
  | { type: 'syncTracks'; tracks: unknown[]; sourceId: string }
  | { type: 'addSource'; source: unknown }
  | { type: 'removeSource'; id: string }
  | { type: 'importSchedule'; parsed: unknown; mode: 'replace' | 'append' }
  | { type: 'addDay'; id: string; label: string }
  | { type: 'updateDay'; id: string; patch: unknown }
  | { type: 'deleteDay'; id: string }
  | { type: 'moveDay'; id: string; delta: number }
  | { type: 'addBlock'; id: string; dayId: string; block?: unknown }
  | { type: 'updateBlock'; id: string; patch: unknown }
  | { type: 'deleteBlock'; id: string }
  | { type: 'moveBlockToDay'; id: string; dayId: string }
  | { type: 'sortDayByTime'; dayId: string }
  | { type: 'assign'; blockId: string; entryIds: string[]; trackIds: string[]; index?: number }
  | { type: 'unassign'; blockId: string; entryId: string }
  | { type: 'moveEntry'; fromBlockId: string; entryId: string; toBlockId: string; toIndex: number }
  | { type: 'reorderEntry'; blockId: string; entryId: string; delta: number }
  | { type: 'setEntryNote'; blockId: string; entryId: string; note: string }
  | { type: 'clearBlockEntries'; blockId: string }
  | { type: 'renamePlan'; name: string }

/** Someone currently connected to the plan. */
export type Presence = {
  collaboratorId: string
  displayName: string
  role: Role
}

/** How the plan's master order stands relative to Spotify. */
export type SyncState = {
  status: 'idle' | 'pending' | 'syncing' | 'synced' | 'paused' | 'off'
  /** Epoch ms of the last successful push, or null if never. */
  lastSyncedAt: number | null
  /** Why syncing is paused — shown to the user verbatim. */
  error: string | null
  /** Name of the Spotify playlist being kept in step, when known. */
  playlistName: string | null
}

/** Browser → server. */
export type ClientMessage =
  | { t: 'hello'; since: number }
  | { t: 'ops'; ops: Op[]; clientSeq: number }
  | { t: 'ping' }

/** Server → browser. */
export type ServerMessage =
  /** Full state, sent on connect or whenever a client has fallen too far behind. */
  | { t: 'snapshot'; rev: number; doc: unknown; you: Presence; peers: Presence[]; sync: SyncState }
  /** Ops applied by someone else (or your own, echoed back with their rev). */
  | { t: 'ops'; rev: number; ops: Op[]; from: string }
  /** Your ops were accepted; ties your clientSeq to the server revision. */
  | { t: 'ack'; rev: number; clientSeq: number }
  | { t: 'presence'; peers: Presence[] }
  | { t: 'sync'; sync: SyncState }
  | { t: 'error'; message: string; fatal?: boolean }

/** Max ops accepted in one message, so a bad client cannot flood the DO. */
export const MAX_OPS_PER_MESSAGE = 200
